services:
  mongodb:
    image: mongo:4.4.6
    container_name: hackathon-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: aihackathon
      MONGO_INITDB_ROOT_PASSWORD: changeme123
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
    driver: local
